version: '3.8'

services:
  spark-performance-insight:
    image: apache/spark:4.0.2-java21
    container_name: spark-performance-insight
    hostname: spark-performance-insight
    user: root
    entrypoint: [""]
    ports:
      - "0.0.0.0:18080:18080"
      - "0.0.0.0:18081:18081"
    volumes:
      - ./workspace:/opt/spark/work-dir/workspace
      - ./config:/opt/spark/work-dir/workspace/config
    networks:
      - spark-performance-insight-net
    command: /bin/bash /opt/spark/work-dir/workspace/entrypoint.sh

volumes:
  master_data:

networks:
  spark-performance-insight-net:
    driver: bridge