spring:
  config:
    import: "optional:classpath:application-core.yml"
  ai:
    mcp:
      server:
        http:
          enabled: ${MCP_ENABLED:true}

server:
  port: 18082

insight:
  mcp:
    enabled: ${MCP_ENABLED:true}
